[package]
name = "rust_datarace"
version = "0.1.0"
edition = "2021"


[dependencies]
configparser = "3.0.0"
walkdir = "2.3.2"
zip = "0.5"
unicode-segmentation = "1.9.0"
unicode-normalization = "0.1.19"
caseless = "0.2.1"